spring.application.name=skill14

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/skill14
spring.datasource.username=root
spring.datasource.password=1010

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true